export const tileData = [
   {
      "path":"/images/kingcrown.jpg"
   },
   {
      "path":"/images/partyhat1.jpg"
   },
   {
      "path":"/images/baloonRed.jpg"
   },
   {
      "path":"/images/sports_soccerball.jpg"
   },
   {
      "path":"/images/sports_.jpg"
   },
   {
      "path":"/images/social_facebookLike.jpg"
   },
   {
      "path":"/images/schoolbus.jpg"
   },
   {
      "path":"/images/snowflake.jpg"
   },
   {
      "path":"/images/social_tiktokIcon.jpg"
   },
   {
      "path":"/images/partyhat2.jpg"
   },
   {
      "path":"/images/drink_Margarita.jpg"
   },
   {
      "path":"/images/partyhat3.jpg"
   },
   {
      "path":"/images/emoji_4.jpg"
   },
   {
      "path":"/images/star_Stars.jpg"
   },
   {
      "path":"/images/star_redStar.jpg"
   },
   {
      "path":"/images/star_blueStar.jpg"
   },
   {
      "path":"/images/sports_football.jpg"
   },
   {
      "path":"/images/emoji_1.jpg"
   },
   {
      "path":"/images/emoji_3.jpg"
   },
   {
      "path":"/images/presentOrgane.jpg"
   },
   {
      "path":"/images/emoji_2.jpg"
   },
   {
      "path":"/images/social_InstaIcon.jpg"
   },
   {
      "path":"/images/drink_cherry.jpg"
   },
   {
      "path":"/images/drink_rootbeer.jpg"
   },
   {
      "path":"/images/prayingHands.jpg"
   },
   {
      "path":"/images/candle.jpg"
   },
   {
      "path":"/images/drink_hawai.jpg"
   },
   {
      "path":"/images/drink_starbucks.jpg"
   },
   {
      "path":"/images/butterfly.jpg"
   },
   {
      "path":"/images/baloonBlue.jpg"
   },
   {
      "path":"/images/lipStick.jpg"
   },
   {
      "path":"/images/emoji_kissFace.jpg"
   },
   {
      "path":"/images/presentPink.jpg"
   },
   {
      "path":"/images/Cake9.jpg"
   },
   {
      "path":"/images/PrincessCrown.jpg"
   },
   {
      "path":"/images/social_youtube.jpg"
   },
   {
      "path":"/images/Cake8.jpg"
   },
   {
      "path":"/images/Cake5.jpg"
   },
   {
      "path":"/images/Cake4.jpg"
   },
   {
      "path":"/images/social_pinterest.jpg"
   },
   {
      "path":"/images/hearts_1.jpg"
   },
   {
      "path":"/images/social_PinkSnap.jpg"
   },
   {
      "path":"/images/HairDryer.jpg"
   },
   {
      "path":"/images/social_snapYellow.jpg"
   },
   {
      "path":"/images/sports_foamFinger.jpg"
   },
   {
      "path":"/images/social_phone.JPG"
   },
   {
      "path":"/images/emoji_PartyEmoji.jpg"
   },
   {
      "path":"/images/Heart_giantredHeart.jpg"
   },
   {
      "path":"/images/carnival_clowns1.jpg"
   },
   {
      "path":"/images/baloonDouble.JPG"
   },
   {
      "path":"/images/Cake3.jpg"
   },
   {
      "path":"/images/presentYellow.jpg"
   },
   {
      "path":"/images/Cake2.jpg"
   },
   {
      "path":"/images/Unicorn1.jpg"
   },
   {
      "path":"/images/present_color.jpg"
   },
   {
      "path":"/images/gus.jpg"
   },
   {
      "path":"/images/Cake1.jpg"
   },
   {
      "path":"/images/partyRyan.JPG"
   },
   {
      "path":"/images/baloonMulti.jpg"
   },
   {
      "path":"/images/Unicorn2.jpg"
   },
   {
      "path":"/images/drink_beer.jpg"
   },
   {
      "path":"/images/ryansworld.jpg"
   },
   {
      "path":"/images/social_youtubeIcon.jpg"
   },
   {
      "path":"/images/social_computer2.jpg"
   },
   {
      "path":"/images/baloonYellow.jpg"
   },
   {
      "path":"/images/carnival_Birthday.jpg"
   },
   {
      "path":"/images/sports_basketball.jpg"
   },
   {
      "path":"/images/heels.jpg"
   },
   {
      "path":"/images/Carnival_.jpg"
   },
   {
      "path":"/images/carnival_RollerCoaster.jpg"
   },
   {
      "path":"/images/rainbow.jpg"
   },
   {
      "path":"/images/printers.jpg"
   },
   {
      "path":"/images/stapler.jpg"
   },
   {
      "path":"/images/apple.jpg"
   },
   {
      "path":"/images/calculator.jpg"
   }
]

export const babyPaths = [
   {
      "path":"/images/baby_itsaboy.jpg"
   },
   {
      "path":"/images/baby_waddleBoy.JPG"
   },
   {
      "path":"/images/babywaddle.jpg"
   },
   {
      "path":"/images/babybirdblue.jpg"
   },
   {
      "path":"/images/baby_pacifier.jpg"
   },
   {
      "path":"/images/babybirdgirl.jpg"
   }
]

export const HalloweenPaths = [
   {
      "path":"/images/halloween6.jpg"
   },
   {
      "path":"/images/halloween5.jpg"
   },
   {
      "path":"/images/halloween4.jpg"
   },
   {
      "path":"/images/halloween1.jpg"
   },
   {
      "path":"/images/halloween3.jpg"
   },
   {
      "path":"/images/halloween2.jpg"
   }
]

export default {
  tileData, babyPaths, HalloweenPaths
}