export const tileData = [
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/kingcrown.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/partyhat1.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/baloonRed.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/sports_soccerball.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/sports_.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_facebookLike.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/schoolbus.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/snowflake.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_tiktokIcon.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/partyhat2.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/drink_Margarita.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/partyhat3.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/emoji_4.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/star_Stars.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/star_redStar.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/star_blueStar.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/sports_football.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/emoji_1.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/emoji_3.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/presentOrgane.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/emoji_2.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_InstaIcon.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/drink_cherry.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/drink_rootbeer.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/prayingHands.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/candle.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/drink_hawai.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/drink_starbucks.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/butterfly.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/baloonBlue.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/lipStick.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/emoji_kissFace.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/presentPink.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Cake9.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/PrincessCrown.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_youtube.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Cake8.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Cake5.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Cake4.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_pinterest.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/hearts_1.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_PinkSnap.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/HairDryer.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_snapYellow.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/sports_foamFinger.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_phone.JPG?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/emoji_PartyEmoji.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Heart_giantredHeart.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/carnival_clowns1.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/baloonDouble.JPG?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Cake3.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/presentYellow.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Cake2.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Unicorn1.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/present_color.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/gus.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Cake1.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/partyRyan.JPG?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/baloonMulti.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Unicorn2.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/drink_beer.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/ryansworld.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_youtubeIcon.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/social_computer2.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/baloonYellow.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/carnival_Birthday.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/sports_basketball.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/heels.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/Carnival_.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/carnival_RollerCoaster.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/rainbow.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/printers.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/stapler.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/apple.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/calculator.jpg?raw=true"
   }
]

export const babyPaths = [
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/baby_itsaboy.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/baby_waddleBoy.JPG?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/babywaddle.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/babybirdblue.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/baby_pacifier.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/babybirdgirl.jpg?raw=true"
   }
]

export const HalloweenPaths = [
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/halloween6.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/halloween5.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/halloween4.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/halloween1.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/halloween3.jpg?raw=true"
   },
   {
      "path":"https://github.com/adolfoherrera1417/party-zone/blob/main/public/Images/halloween2.jpg?raw=true"
   }
]

export default {
  tileData, babyPaths, HalloweenPaths
}